<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tapia Academy</title>
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/home.css">
</head>

<body>
    <header>
        <div class="header">
            <nav>
                <ul>
                    <li><a href="index.phtml" class="active">Home</a></li>
                    <li><a href="turnos.phtml">Turnos</a></li>
                    <li><a href="canchas.phtml">Canchas</a></li>
                </ul>
            </nav>
            <img src="../img/logo-padel.png" alt="academy logo" class="logo">
            <a href="form_login.phtml" class="btn-login">Login</a>
        </div>
    </header>
    <main>
        <section class="hero">
            <div class="hero-container">
                <h1>Tu cancha te espera</h1>
            </div>
            <div class="hero-container">
                <p>Elige tu horario, reserva tu cancha y empieza a jugar hoy mismo. ¡Tu partido te espera!</p>
            </div>
            <a href="" class="btn-hero">Reservar Turno</a>
        </section>
        <section class="court">
            <div class="court-container">
                <h2>Nuestras Canchas</h2>
                <div class="line"></div>
                <div class="grid">
                    <div class="cards">
                        <img src="./img/court-1.jpg" alt="">
                        <h3>Cancha Profesional</h3>
                        <p>Superficie cesped sintetico - Pared de blindex</p>
                    </div>
                    <div class="cards">
                        <img src="./img/court-2.jpg" alt="">
                        <h3>Cancha Single</h3>
                        <p>Superficie cesped sintetico - Pared de blindex</p>
                    </div>
                    <div class="cards">
                        <img src="./img/court-3.jpg" alt="">
                        <h3>Cancha Amateur</h3>
                        <p>Superficie cesped sintetico - Pared de cemento</p>
                    </div>
                </div>
        </section>
    </main>
    <footer>
        <div class="footer">
            <div>
                <ul>
                    <li><img src="./img/map-pin-solid-full.svg" alt="map-icon" class="img-footer"></li>
                    <li>2494320564</li>
                </ul>
                <ul>
                    <li><img src="./img/phone-solid-full.svg" alt="phone-icon" class="img-footer"></li>
                    <li>Av. Avellaneda 671</li>
                </ul>
            </div>
            <p>© 2025-Tapia Academy</p>
            <div>
                <ul>
                    <li><img src="../img/instagram-brands-solid-full.svg" alt="ig-icon" class="img-footer"></li>
                    <li>tapia.academy</li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>